import * as THREE from 'three';
import { Loader as ClassLoader, createClass, updateLabelFontSizes, createClassData, updateClassData, normalizeClassData, validateClassData } from './hbds_class.js';
import { Loader as HyperClassLoader, createHyperClass, updateLabelFontSizes as updateHyperClassLabelFontSizes, createHyperclassData, updateHyperclassData, normalizeHyperclassData, validateHyperclassData, addChildData, removeChildData } from './hbds_hyperclass_class.js';
import { createLinkBetweenClass, updateLinkFontSizes, recalculateAllLinks, createLinkData, updateLinkData, normalizeLinkData, validateLinkData } from './hbds_class_link.js';
import { createLinkBetweenHyperClass, updateLinkFontSizes as updateHyperClassLinkFontSizes } from './hbds_hyperclass_link.js';

let data = { hypergraph: { class: [], link: [] } };
const history=[];
const modelRuntime={ classById:new Map(), linkGroups:[], diagramGroup:null, draggableObjects:[] };
const clone=(v)=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
const nextId=(p)=>`${p}_${Math.random().toString(36).slice(2,8)}`;
export const getData=()=>data;
export function normalizeData(inputData){
  const m=clone(inputData||{}); m.hypergraph=m.hypergraph||{};
  m.hypergraph.class=Array.isArray(m.hypergraph.class)?m.hypergraph.class:[];
  m.hypergraph.link=Array.isArray(m.hypergraph.link)?m.hypergraph.link:[];
  const ids=new Set(); const byId=new Map();
  m.hypergraph.class=m.hypergraph.class.map((n,i)=>{let x=clone(n||{}); if(x.type==='hyperclass') x=normalizeHyperclassData(x); else x=normalizeClassData(x); x.id=x.id??nextId('node'); while(ids.has(x.id)) x.id=nextId('node'); ids.add(x.id); x.name=x.name||`Node ${i+1}`; x.attributes=Array.isArray(x.attributes)?x.attributes:[]; if(x.type==='hyperclass') x.children=Array.isArray(x.children)?x.children:[]; byId.set(x.id,x); return x;});
  for(const n of m.hypergraph.class){ if(n.parentClassId && (!byId.has(n.parentClassId)||byId.get(n.parentClassId).type!=='hyperclass')) n.parentClassId=null; }
  for(const h of m.hypergraph.class.filter(n=>n.type==='hyperclass')){ h.children=(h.children||[]).filter(id=>byId.has(id)); for(const cid of h.children){byId.get(cid).parentClassId=h.id;} }
  m.hypergraph.link=m.hypergraph.link.map(l=>normalizeLinkData(l)).filter(l=>l.sourceClassId&&l.targetClassId&&byId.has(l.sourceClassId)&&byId.has(l.targetClassId));
  return m;
}
export function validateData(currentData=data){const e=[],w=[]; const hg=currentData?.hypergraph; if(!Array.isArray(hg?.class)) e.push('missing hypergraph.class'); if(!Array.isArray(hg?.link)) e.push('missing hypergraph.link'); const ids=new Set(); const byId=new Map(); for(const c of hg?.class||[]){if(ids.has(c.id)) e.push(`duplicate class id ${c.id}`); ids.add(c.id); byId.set(c.id,c); if(!Array.isArray(c.attributes)) e.push(`invalid attributes for ${c.id}`);} const lids=new Set(); for(const l of hg?.link||[]){ if(l.id&&lids.has(l.id)) e.push(`duplicate link id ${l.id}`); if(l.id) lids.add(l.id); if(!byId.has(l.sourceClassId)) e.push(`missing link source ${l.sourceClassId}`); if(!byId.has(l.targetClassId)) e.push(`missing link target ${l.targetClassId}`);} return {valid:e.length===0,errors:e,warnings:w};}
export function refreshSceneFromData(context){ if(!context) return; const {scene,setDiagramGroup,diagramGroup,setDragControls,dragControls,draggableObjects=[]}=context; if(diagramGroup){scene?.remove(diagramGroup); diagramGroup.traverse(o=>{if(o.geometry) o.geometry.dispose?.(); if(o.material) o.material.dispose?.(); if(o.isCSS2DObject) o.element?.remove?.();});}
  if(dragControls){dragControls.dispose(); setDragControls?.(null);} const dg=new THREE.Group(); scene?.add(dg); setDiagramGroup?.(dg); modelRuntime.diagramGroup=dg; modelRuntime.classById.clear(); modelRuntime.linkGroups=[];
  for(const cd of data.hypergraph.class){ const r=cd.type==='hyperclass'?createHyperClass(null,cd):createClass(cd); const m=r.classMesh; m.userData={...m.userData,hbdsId:cd.id,modelData:clone(cd),isClassLike:true,isHyperClass:cd.type==='hyperclass',isHbdsClass:true}; if(cd.type!=='hyperclass'&&cd.position) m.position.set(cd.position.x||0,cd.position.y||0,cd.position.z||0); dg.add(m); modelRuntime.classById.set(cd.id,m);} 
  for(const cd of data.hypergraph.class){ if(!cd.parentClassId) continue; const p=modelRuntime.classById.get(cd.parentClassId), ch=modelRuntime.classById.get(cd.id); if(p&&ch){const wp=ch.getWorldPosition(new THREE.Vector3()); p.worldToLocal(wp); dg.remove(ch); ch.position.copy(wp); p.add(ch);} }
  for(const ld of data.hypergraph.link){ const s=modelRuntime.classById.get(ld.sourceClassId), t=modelRuntime.classById.get(ld.targetClassId); if(!s||!t) continue; const r=(s.userData.isHyperClass||t.userData.isHyperClass)?createLinkBetweenHyperClass(dg,s,t,ld):createLinkBetweenClass(ld,modelRuntime.classById); if(!r) continue; r.linkGroup.userData={...r.linkGroup.userData,linkData:clone(ld),sourceClassId:ld.sourceClassId,targetClassId:ld.targetClassId,isHBDSLink:true,isHbdsLink:true}; dg.add(r.linkGroup); modelRuntime.linkGroups.push(r.linkGroup);} 
  draggableObjects.length=0; for(const cd of data.hypergraph.class){ if(!cd.parentClassId){const o=modelRuntime.classById.get(cd.id); if(o) draggableObjects.push(o);} }
  modelRuntime.draggableObjects=draggableObjects;
  context.setupDragControls?.(); recalculateAllLinks(); updateLabelFontSizes(context.camera); updateHyperClassLabelFontSizes(context.camera, context.renderer); updateLinkFontSizes(context.camera); updateHyperClassLinkFontSizes(context.camera, context.renderer); context.renderOnce?.(); }
export function updateLayoutFromData(context){ recalculateAllLinks(); updateLabelFontSizes(context.camera); updateHyperClassLabelFontSizes(context.camera, context.renderer); updateLinkFontSizes(context.camera); updateHyperClassLinkFontSizes(context.camera, context.renderer); context.renderOnce?.(); }
export function commitDataChange(operationName, updater, options={}){ const before=clone(data); const result=updater(data); data=normalizeData(data); const v=validateData(data); if(!v.valid && options.rollbackOnError!==false){ data=before; throw new Error(`Invalid data after ${operationName}: ${v.errors.join('; ')}`);} if(options.refresh!==false) refreshSceneFromData(options.context); if(options.optimizeLayout===true) updateLayoutFromData(options.context); if(options.saveHistory!==false) history.push({operationName,before,after:clone(data)}); return result; }
export function setData(nextData, options={}){ data=normalizeData(nextData); const v=validateData(data); if(!v.valid) throw new Error(v.errors.join('; ')); if(options.refresh!==false) refreshSceneFromData(options.context); return getData(); }
export function resetData(options={}){ return setData({hypergraph:{class:[],link:[]}},options); }
export function readClass(id){return data.hypergraph.class.find(c=>c.id===id)||null;} export const readHyperclass=readClass;
export function createClass(input,options={}){ return commitDataChange('createClass',d=>{ const c=createClassData(input); d.hypergraph.class.push(c); if(c.parentClassId) addChildToHyperclass(c.parentClassId,c.id,{...options,refresh:false,saveHistory:false}); return c;},options); }
export function updateClass(id,patch,options={}){ return commitDataChange('updateClass',d=>{ const i=d.hypergraph.class.findIndex(c=>c.id===id&&c.type!=='hyperclass'); if(i<0) throw new Error('class not found'); d.hypergraph.class[i]=updateClassData(d.hypergraph.class[i],patch); return d.hypergraph.class[i];},options); }
export function deleteLinksForNode(id,options={}){ return commitDataChange('deleteLinksForNode',d=>{ d.hypergraph.link=d.hypergraph.link.filter(l=>l.sourceClassId!==id&&l.targetClassId!==id);},options); }
export function deleteClass(id,options={}){ return commitDataChange('deleteClass',d=>{ const node=d.hypergraph.class.find(c=>c.id===id); if(!node) return false; d.hypergraph.class=d.hypergraph.class.filter(c=>c.id!==id); d.hypergraph.class.filter(c=>c.type==='hyperclass').forEach(h=>h.children=removeChildData(h,id).children); d.hypergraph.link=d.hypergraph.link.filter(l=>l.sourceClassId!==id&&l.targetClassId!==id); return true;},options); }
export function createHyperclass(input,options={}){ return commitDataChange('createHyperclass',d=>{ const h=createHyperclassData(input); d.hypergraph.class.push(h); if(h.parentClassId) addChildToHyperclass(h.parentClassId,h.id,{...options,refresh:false,saveHistory:false}); return h;},options); }
export function updateHyperclass(id,patch,options={}){ return commitDataChange('updateHyperclass',d=>{ const i=d.hypergraph.class.findIndex(c=>c.id===id&&c.type==='hyperclass'); if(i<0) throw new Error('hyperclass not found'); d.hypergraph.class[i]=updateHyperclassData(d.hypergraph.class[i],patch); return d.hypergraph.class[i];},options); }
export function deleteHyperclass(id,options={cascade:true}){ return commitDataChange('deleteHyperclass',d=>{ const ids=new Set([id]); if(options.cascade!==false){ let changed=true; while(changed){changed=false; for(const c of d.hypergraph.class){ if(c.parentClassId&&ids.has(c.parentClassId)&&!ids.has(c.id)){ids.add(c.id);changed=true;}} } d.hypergraph.class=d.hypergraph.class.filter(c=>!ids.has(c.id)); } else d.hypergraph.class=d.hypergraph.class.filter(c=>c.id!==id).map(c=>c.parentClassId===id?{...c,parentClassId:null}:c); d.hypergraph.link=d.hypergraph.link.filter(l=>!ids.has(l.sourceClassId)&&!ids.has(l.targetClassId)); d.hypergraph.class.filter(c=>c.type==='hyperclass').forEach(h=>h.children=(h.children||[]).filter(cid=>!ids.has(cid))); return true;},options); }
export function addChildToHyperclass(parentId,childId,options={}){ return commitDataChange('addChild',d=>{ const p=d.hypergraph.class.find(c=>c.id===parentId&&c.type==='hyperclass'); const c=d.hypergraph.class.find(c=>c.id===childId); if(!p||!c) throw new Error('invalid parent/child'); p.children=addChildData(p,childId).children; c.parentClassId=parentId; },options);}
export function removeChildFromHyperclass(parentId,childId,options={}){ return commitDataChange('removeChild',d=>{ const p=d.hypergraph.class.find(c=>c.id===parentId&&c.type==='hyperclass'); const c=d.hypergraph.class.find(c=>c.id===childId); if(!p||!c) return false; p.children=removeChildData(p,childId).children; if(c.parentClassId===parentId) c.parentClassId=null; return true;},options);}
export const moveChildToHyperclass=(cid,pid,options={})=>commitDataChange('moveChild',d=>{const c=d.hypergraph.class.find(n=>n.id===cid); if(!c) throw new Error('child not found'); d.hypergraph.class.filter(n=>n.type==='hyperclass').forEach(h=>h.children=(h.children||[]).filter(x=>x!==cid)); if(pid){const p=d.hypergraph.class.find(n=>n.id===pid&&n.type==='hyperclass'); if(!p) throw new Error('parent not hyperclass'); p.children.push(cid); c.parentClassId=pid;} else c.parentClassId=null;},options);
export function readAttributes(ownerId){return readClass(ownerId)?.attributes||[];}
export function createAttribute(ownerId,attributeInput,options={}){ return commitDataChange('createAttribute',d=>{ const o=d.hypergraph.class.find(c=>c.id===ownerId); if(!o) throw new Error('owner not found'); o.attributes=o.attributes||[]; if(o.attributes.length&&typeof o.attributes[0]==='string') o.attributes.push(attributeInput?.name||String(attributeInput)); else o.attributes.push(typeof attributeInput==='string'?attributeInput:{id:attributeInput?.id||nextId('att'),name:attributeInput?.name||'attribute'}); },options);}
export const updateAttribute=(ownerId,key,patch,options={})=>commitDataChange('updateAttribute',d=>{const o=d.hypergraph.class.find(c=>c.id===ownerId); if(!o) throw new Error('owner not found'); const i=typeof key==='number'?key:o.attributes.findIndex(a=>typeof a==='string'?a===key:a.name===key||a.id===key); if(i<0) throw new Error('attribute not found'); o.attributes[i]=typeof o.attributes[i]==='string'?(patch?.name||patch):{...o.attributes[i],...(typeof patch==='string'?{name:patch}:patch)};},options);
export const deleteAttribute=(ownerId,key,options={})=>commitDataChange('deleteAttribute',d=>{const o=d.hypergraph.class.find(c=>c.id===ownerId); if(!o) throw new Error('owner not found'); const i=typeof key==='number'?key:o.attributes.findIndex(a=>typeof a==='string'?a===key:a.name===key||a.id===key); if(i>=0) o.attributes.splice(i,1);},options);
export const readLink=(idOrPred)=>typeof idOrPred==='function'?data.hypergraph.link.find(idOrPred)||null:data.hypergraph.link.find(l=>l.id===idOrPred)||null;
export const createLink=(input,options={})=>commitDataChange('createLink',d=>{const l=createLinkData(input); const byId=new Map(d.hypergraph.class.map(c=>[c.id,c])); const v=validateLinkData(l,byId); if(!v.valid) throw new Error(v.errors.join('; ')); d.hypergraph.link.push(l); return l;},options);
export const updateLink=(idOrPred,patch,options={})=>commitDataChange('updateLink',d=>{const i=d.hypergraph.link.findIndex(l=>typeof idOrPred==='function'?idOrPred(l):l.id===idOrPred); if(i<0) throw new Error('link not found'); d.hypergraph.link[i]=updateLinkData(d.hypergraph.link[i],patch);},options);
export const deleteLink=(idOrPred,options={})=>commitDataChange('deleteLink',d=>{d.hypergraph.link=d.hypergraph.link.filter(l=>!(typeof idOrPred==='function'?idOrPred(l):l.id===idOrPred||(idOrPred?.sourceClassId===l.sourceClassId&&idOrPred?.targetClassId===l.targetClassId)));},options);
export async function loadAndRenderScene(modelName, context){ const raw=await HyperClassLoader.load(modelName).catch(()=>ClassLoader.load(modelName)); setData(raw,{context,refresh:true}); return getData(); }
export function saveScene(context, options={}){ const blob=new Blob([JSON.stringify(getData(),null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=options.fileName||'hbds_saved_model.json'; a.click(); URL.revokeObjectURL(url); return getData(); }
export async function optimizeAndRefreshLayout(context, options={}){ refreshSceneFromData(context); updateLayoutFromData(context,options); }
