import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { DragControls } from 'three/addons/controls/DragControls.js';
import { CSS2DRenderer } from 'three/addons/renderers/CSS2DRenderer.js';
import { createClass, updateLabelFontSizes } from './hbds_class.js';
import { createHyperClass, updateLabelFontSizes as updateHyperClassLabelFontSizes } from './hbds_hyperclass_class.js';
import { createLinkBetweenClass, updateLinkFontSizes, recalculateAllLinks } from './hbds_class_link.js';
import { createLinkBetweenHyperClass, updateLinkFontSizes as updateHyperClassLinkFontSizes } from './hbds_hyperclass_link.js';
import { optimizeAndRefreshLayout, saveScene } from './hbds_model.js';
const TEST_MODEL_OPTIONS=[{label:'Empty Dynamic Model',value:''},{label:'Transportation Links',value:'./test_models/transportation_links.json'}];
let dynamicModel={hypergraph:{class:[],link:[]}},nextId=1,nextClassNumber=1,nextHyperclassNumber=1,nextAttributeNumber=1,nextLinkNumber=1;
let scene,camera,renderer,labelRenderer,orbitControls,dragControls,diagramGroup; const nodeMeshById=new Map(),draggableObjects=[];
let selectedElementId=null,selectedParentHyperclassId=null,selectedAttributeOwnerId=null,selectedLinkSourceId=null,selectedLinkTargetId=null,linkPickMode='source',dragUntil=0;
const getDefaultClassRendering=()=>({class:{color:'#FFFFFF',material:'flat',borderColor:'#000000',borderWidth:0.02,cornerRadius:0.1,opacity:0.22},attributes:{checkboxColor:'#A9A9A9',checkboxMaterial:'flat',shape:'circle',size:{width:0.14,height:0.14}},connections:{lineColor:'#000000',lineWidth:0.01},textColor:'#000000'});
const getDefaultHyperclassRendering=()=>({class:{color:'#FFFFFF',material:'flat',borderColor:'#000000',borderWidth:0.02,cornerRadius:0.3,opacity:0.12},attributes:{checkboxColor:'#FFFFFF',checkboxMaterial:'flat',shape:'circle',size:{width:0.14,height:0.14}},connections:{lineColor:'#000000',lineWidth:0.01},textColor:'#000000'});
const getDefaultLinkRendering=(labelText='')=>({lineColor:'#000000',lineWidth:2,lineStyle:'solid',curveOffset:0.45,arrowheadVisibility:true,arrowheadType:'triangle',arrowheadSize:0.22,labelText,labelFontSize:13,labelColor:'#000000',labelBackgroundColor:'rgba(255,255,255,0.95)',labelPositionAlongPath:0.5,labelOffsetFromPath:0.2,labelRotationBehavior:'follow',zIndex:8});
function ensureReadableRendering(cd){const c=(cd.rendering?.class?.color||'#fff').replace('#','');const r=parseInt(c.slice(0,2)||'ff',16),g=parseInt(c.slice(2,4)||'ff',16),b=parseInt(c.slice(4,6)||'ff',16);const l=(0.2126*r+0.7152*g+0.0722*b)/255;cd.rendering.textColor=l<0.45?'#FFFFFF':'#000000';if(cd.rendering.class.material==='metallic') cd.rendering.class.material='flat';}
function applyLocalClassDefaults(cd){const base=cd.type==='hyperclass'?getDefaultHyperclassRendering():getDefaultClassRendering();cd.type=cd.type||'roundedRectangle';cd.position=cd.position||{x:0,y:0,z:0};cd.size=cd.size||{width:1.2,height:1.6};cd.rendering={...base,...(cd.rendering||{})};cd.attributes=Array.isArray(cd.attributes)?cd.attributes:[];cd.children=Array.isArray(cd.children)?cd.children:[];ensureReadableRendering(cd);return cd;}
const applyLocalLinkDefaults=(l)=>{l.rendering={...getDefaultLinkRendering(l.rendering?.labelText||l.id||`link${nextLinkNumber}`),...(l.rendering||{})}; return l;};
function applyLocalModelDefaults(m){m.hypergraph=m.hypergraph||{class:[],link:[]};m.hypergraph.class=(m.hypergraph.class||[]).map(applyLocalClassDefaults);m.hypergraph.link=(m.hypergraph.link||[]).map(applyLocalLinkDefaults);return m;}
function setupLighting(scene){scene.background=new THREE.Color('#f4f4f4');scene.add(new THREE.AmbientLight(0xffffff,1.15));const h=new THREE.HemisphereLight(0xffffff,0xdde6ff,0.75);h.position.set(0,0,10);scene.add(h);const k=new THREE.DirectionalLight(0xffffff,0.85);k.position.set(4,6,10);scene.add(k);const f=new THREE.DirectionalLight(0xffffff,0.45);f.position.set(-6,-4,8);scene.add(f);const fr=new THREE.DirectionalLight(0xffffff,0.35);fr.position.set(0,0,10);scene.add(fr);}
function findClassDataById(id){return dynamicModel.hypergraph.class.find(c=>c.id===Number(id));}
function setSelectOptions(selectId,items,selectedValue,placeholder){const el=document.getElementById(selectId);el.innerHTML='';if(placeholder){const op=document.createElement('option');op.value='';op.textContent=placeholder;el.appendChild(op);}items.forEach(item=>{const op=document.createElement('option');op.value=String(item.id);op.textContent=`${item.name} (#${item.id})`;el.appendChild(op);});el.value=selectedValue!=null?String(selectedValue):'';}
function getSelectValue(selectId){const v=document.getElementById(selectId).value;return v===''?null:Number(v);}
function updateSmartMenus(){const nodes=dynamicModel.hypergraph.class,hy=nodes.filter(n=>n.type==='hyperclass');setSelectOptions('selected-element-select',nodes,selectedElementId,'-- Select element --');setSelectOptions('parent-hyperclass-select',hy,selectedParentHyperclassId,'-- No parent hyperclass --');setSelectOptions('attribute-owner-select',nodes,selectedAttributeOwnerId,'-- Select attribute owner --');setSelectOptions('link-source-select',nodes,selectedLinkSourceId,'-- Select source --');setSelectOptions('link-target-select',nodes,selectedLinkTargetId,'-- Select target --');}
function collectDraggableObjects(){draggableObjects.length=0; nodeMeshById.forEach(o=>{if(o?.userData?.isClassLike||o?.userData?.hbdsId) draggableObjects.push(o);});}
function renderModel(){if(diagramGroup) scene.remove(diagramGroup); diagramGroup=new THREE.Group();scene.add(diagramGroup);nodeMeshById.clear();dynamicModel.hypergraph.class.forEach(cd=>{const b=cd.type==='hyperclass'?createHyperClass(null,cd):createClass(cd);const m=b.classMesh;m.userData={hbdsId:cd.id,isClassLike:true};nodeMeshById.set(cd.id,m);diagramGroup.add(m);});dynamicModel.hypergraph.class.forEach(cd=>{if(cd.parentClassId){const p=nodeMeshById.get(cd.parentClassId),ch=nodeMeshById.get(cd.id);if(p&&ch){const wp=ch.getWorldPosition(new THREE.Vector3());p.worldToLocal(wp);diagramGroup.remove(ch);ch.position.copy(wp);p.add(ch);}}});dynamicModel.hypergraph.link.forEach(ld=>{const s=nodeMeshById.get(ld.sourceClassId),t=nodeMeshById.get(ld.targetClassId);if(!s||!t) return;const h=(findClassDataById(ld.sourceClassId)?.type==='hyperclass'||findClassDataById(ld.targetClassId)?.type==='hyperclass')?createLinkBetweenHyperClass(diagramGroup,s,t,ld):createLinkBetweenClass(ld,nodeMeshById);if(h) diagramGroup.add(h.linkGroup);});collectDraggableObjects();setupDrag();refresh();}
function updateModelPositionFromObject(o){const cd=findClassDataById(o.userData.hbdsId);if(!cd) return;const pos=o.parent===diagramGroup?o.position:o.getWorldPosition(new THREE.Vector3());cd.position={x:pos.x,y:pos.y,z:pos.z};}
function constrainDraggedObjectToParent(o){const cd=findClassDataById(o.userData.hbdsId);if(!cd?.parentClassId) return;const p=findClassDataById(cd.parentClassId);if(!p) return;const hw=(p.size?.width||4)/2-0.6,hh=(p.size?.height||3)/2-0.6;o.position.x=Math.max(-hw,Math.min(hw,o.position.x));o.position.y=Math.max(-hh,Math.min(hh,o.position.y));}
function setupDrag(){if(dragControls) dragControls.dispose();dragControls=new DragControls(draggableObjects,camera,labelRenderer.domElement);dragControls.transformGroup=false;dragControls.addEventListener('dragstart',()=>{orbitControls.enabled=false;dragUntil=Date.now()+500;});dragControls.addEventListener('drag',e=>{constrainDraggedObjectToParent(e.object);updateModelPositionFromObject(e.object);recalculateAllLinks();renderOnce();});dragControls.addEventListener('dragend',e=>{updateModelPositionFromObject(e.object);orbitControls.enabled=true;recalculateAllLinks();updateJsonPreview();refresh();});}
function selectElement(id){selectedElementId=id;selectedAttributeOwnerId=id;const el=findClassDataById(id);if(el?.type==='hyperclass') selectedParentHyperclassId=id;updateSmartMenus();}
function createLink(sourceId,targetId){if(!sourceId||!targetId||sourceId===targetId) return false;dynamicModel.hypergraph.link.push(applyLocalLinkDefaults({id:`link${nextLinkNumber}`,sourceClassId:sourceId,targetClassId:targetId,rendering:{labelText:`link${nextLinkNumber++}`}}));renderModel();return true;}
function handleClick(id){if(Date.now()<dragUntil) return;selectElement(id);if(linkPickMode==='source'){selectedLinkSourceId=id;selectedLinkTargetId=null;linkPickMode='target';}else if(id!==selectedLinkSourceId){selectedLinkTargetId=id;createLink(selectedLinkSourceId,selectedLinkTargetId);selectedLinkSourceId=id;selectedLinkTargetId=null;linkPickMode='target';}updateSmartMenus();}
function addClass(type='roundedRectangle'){const pid=selectedParentHyperclassId||null,id=nextId++;const c=applyLocalClassDefaults({id,name:type==='hyperclass'?`hyperclass${nextHyperclassNumber++}`:`class${nextClassNumber++}`,type:type==='hyperclass'?'hyperclass':'roundedRectangle',position:{x:0,y:0,z:0},size:type==='hyperclass'?{width:4,height:3.2}:{width:1.2,height:1.6},attributes:[],children:[]});if(pid){c.parentClassId=pid;const p=findClassDataById(pid);if(p){p.children=p.children||[];p.children.push(id);c.position={x:0,y:0,z:0};}}dynamicModel.hypergraph.class.push(c);renderModel();selectElement(id);}
function refresh(){recalculateAllLinks();updateLabelFontSizes(camera);updateHyperClassLabelFontSizes(camera,renderer);updateLinkFontSizes(camera);updateHyperClassLinkFontSizes(camera,renderer);updateSmartMenus();updateJsonPreview();updateStatus();renderOnce();}
function updateJsonPreview(){document.getElementById('json-preview').value=JSON.stringify(dynamicModel,null,2);}
function updateStatus(msg=''){document.getElementById('layout-status').textContent=`Nodes: ${dynamicModel.hypergraph.class.length}\nLinks: ${dynamicModel.hypergraph.link.length}\n${msg}`;}
function fit(){const box=new THREE.Box3().setFromObject(diagramGroup);if(box.isEmpty()) return;const s=box.getSize(new THREE.Vector3()),c=box.getCenter(new THREE.Vector3()),m=Math.max(s.x,s.y,1);camera.position.set(c.x,c.y,m*2);camera.lookAt(c);orbitControls.target.copy(c);orbitControls.update();}
function isAutoOptimizeEnabled(){return !!document.getElementById('auto-optimize-toggle')?.checked;}
function isAutoFitEnabled(){return !!document.getElementById('auto-fit-toggle')?.checked;}
async function recalculateDynamicLayout({fitToModel=false}={}){if(isAutoOptimizeEnabled()){await optimizeAndRefreshLayout({scene,camera,renderer,css2DRenderer:labelRenderer,orbitControls,dragControls,diagramGroup,draggableObjects,renderOnce},{modelName:'dynamic-test-model',source:'dynamic'});refresh();if(fitToModel||isAutoFitEnabled()) fit();return;}refresh();if(fitToModel||isAutoFitEnabled()) fit();}
async function loadTestModel(path){if(!path){dynamicModel=applyLocalModelDefaults({hypergraph:{class:[],link:[]}});renderModel();return;}const r=await fetch(path);dynamicModel=applyLocalModelDefaults(await r.json());nextId=Math.max(0,...dynamicModel.hypergraph.class.map(c=>c.id))+1;renderModel();fit();}
async function initModelMenu(){let opts=TEST_MODEL_OPTIONS;try{const r=await fetch('./test_models/models.json');if(r.ok){const data=await r.json();opts=[{label:'Empty Dynamic Model',value:''},...data.map(d=>({label:d.label,value:d.path}))];}}catch{}const sel=document.getElementById('test-model-select');opts.forEach(o=>{const op=document.createElement('option');op.textContent=o.label;op.value=o.value;sel.appendChild(op);});sel.onchange=async e=>loadTestModel(e.target.value);}
function renderOnce(){renderer.render(scene,camera);labelRenderer.render(scene,camera);}
async function init(){scene=new THREE.Scene();setupLighting(scene);camera=new THREE.PerspectiveCamera(52,(window.innerWidth-360)/window.innerHeight,0.1,2000);camera.position.set(0,0,12);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(window.innerWidth-360,window.innerHeight);document.getElementById('container').appendChild(renderer.domElement);labelRenderer=new CSS2DRenderer();labelRenderer.setSize(window.innerWidth-360,window.innerHeight);labelRenderer.domElement.style.position='fixed';labelRenderer.domElement.style.top='0';labelRenderer.domElement.style.left='0';document.body.appendChild(labelRenderer.domElement);orbitControls=new OrbitControls(camera,renderer.domElement);
renderer.domElement.addEventListener('pointerup',e=>{const rect=renderer.domElement.getBoundingClientRect();const p=new THREE.Vector2(((e.clientX-rect.left)/rect.width)*2-1,-((e.clientY-rect.top)/rect.height)*2+1);const rc=new THREE.Raycaster();rc.setFromCamera(p,camera);const hits=rc.intersectObjects(diagramGroup?.children||[],true);const hit=hits.find(h=>h.object.parent?.userData?.hbdsId||h.object.userData?.hbdsId);const obj=hit?.object.userData?.hbdsId?hit.object:hit?.object.parent; if(obj?.userData?.hbdsId) handleClick(obj.userData.hbdsId);});
document.getElementById('selected-element-select').onchange=e=>{const id=e.target.value?Number(e.target.value):null;if(id) selectElement(id);};
document.getElementById('parent-hyperclass-select').onchange=e=>selectedParentHyperclassId=e.target.value?Number(e.target.value):null;
document.getElementById('attribute-owner-select').onchange=e=>selectedAttributeOwnerId=e.target.value?Number(e.target.value):null;
document.getElementById('link-source-select').onchange=e=>selectedLinkSourceId=e.target.value?Number(e.target.value):null;
document.getElementById('link-target-select').onchange=e=>selectedLinkTargetId=e.target.value?Number(e.target.value):null;
document.getElementById('add-hyperclass-button').onclick=async()=>{addClass('hyperclass');await recalculateDynamicLayout();};document.getElementById('add-class-button').onclick=async()=>{addClass();await recalculateDynamicLayout();};document.getElementById('add-attribute-button').onclick=async()=>{const owner=getSelectValue('attribute-owner-select')||selectedAttributeOwnerId||selectedElementId;if(!owner) return updateStatus('No attribute owner selected');const o=findClassDataById(owner);o.attributes.push(`att${nextAttributeNumber++}`);selectedAttributeOwnerId=owner;renderModel();await recalculateDynamicLayout();};document.getElementById('add-link-button').onclick=async()=>{const s=getSelectValue('link-source-select')||selectedLinkSourceId,t=getSelectValue('link-target-select')||selectedLinkTargetId;if(!createLink(s,t)) return updateStatus('Invalid link source/target');await recalculateDynamicLayout();};document.getElementById('delete-selected-button').onclick=async()=>{if(!selectedElementId) return;dynamicModel.hypergraph.class=dynamicModel.hypergraph.class.filter(c=>c.id!==selectedElementId&&c.parentClassId!==selectedElementId);dynamicModel.hypergraph.link=dynamicModel.hypergraph.link.filter(l=>l.sourceClassId!==selectedElementId&&l.targetClassId!==selectedElementId);selectedElementId=null;renderModel();await recalculateDynamicLayout();};document.getElementById('optimize-layout-button').onclick=async()=>{await optimizeAndRefreshLayout({scene,camera,renderer,css2DRenderer:labelRenderer,orbitControls,dragControls,diagramGroup,draggableObjects,renderOnce},{modelName:'dynamic-test-model',source:'dynamic'});refresh();};document.getElementById('fit-model-button').onclick=async()=>{await recalculateDynamicLayout({fitToModel:true});};document.getElementById('save-model-button').onclick=()=>saveScene({scene,camera,renderer,css2DRenderer:labelRenderer,orbitControls,dragControls,diagramGroup,draggableObjects,renderOnce},{fileName:'dynamic_hbds_test_model.json'});document.getElementById('reset-model-button').onclick=()=>loadTestModel('');document.getElementById('export-json-button').onclick=updateJsonPreview;
await initModelMenu();renderModel();updateStatus('Ready');(function a(){requestAnimationFrame(a);orbitControls.update();renderOnce();})();}
init();